# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from main import encoder


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypter = QtWidgets.QTextEdit(self.centralwidget)
        self.encrypter.setGeometry(QtCore.QRect(10, 160, 201, 51))
        self.encrypter.setObjectName("encrypter")
        self.decrypter = QtWidgets.QTextEdit(self.centralwidget)
        self.decrypter.setGeometry(QtCore.QRect(220, 160, 201, 51))
        self.decrypter.setObjectName("decrypter")
        self.encryptionButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptionButton.setGeometry(QtCore.QRect(130, 220, 75, 23))
        self.encryptionButton.setDefault(False)
        self.encryptionButton.setFlat(False)
        self.encryptionButton.setObjectName("encryptionButton")
        self.decryptionButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptionButton.setGeometry(QtCore.QRect(340, 220, 75, 23))
        self.decryptionButton.setObjectName("decryptionButton")
        self.encrypted = QtWidgets.QLabel(self.centralwidget)
        self.encrypted.setGeometry(QtCore.QRect(20, 270, 181, 111))
        self.encrypted.setText("")
        self.encrypted.setObjectName("encrypted")
        self.decrypted = QtWidgets.QLabel(self.centralwidget)
        self.decrypted.setGeometry(QtCore.QRect(220, 270, 181, 111))
        self.decrypted.setText("")
        self.decrypted.setObjectName("decrypted")
        self.enKey = QtWidgets.QSpinBox(self.centralwidget)
        self.enKey.setGeometry(QtCore.QRect(20, 220, 42, 22))
        self.enKey.setObjectName("enKey")
        self.deKey = QtWidgets.QSpinBox(self.centralwidget)
        self.deKey.setGeometry(QtCore.QRect(220, 220, 42, 22))
        self.deKey.setObjectName("deKey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encryptionButton.setText(_translate("MainWindow", "Encrypt"))
        self.decryptionButton.setText(_translate("MainWindow", "Decrypt"))


